version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: xeneta_db
      POSTGRES_USER: xeneta_user
      POSTGRES_PASSWORD: xeneta_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    volumes:
      - .:/rates-api

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_DB: xeneta_db
      POSTGRES_USER: xeneta_user
      POSTGRES_PASSWORD: xeneta_password

    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: